# Generated by Django 5.2.7 on 2025-10-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Enter your full name', max_length=100)),
                ('email', models.EmailField(help_text='Enter your email address', max_length=254)),
                ('address', models.TextField(help_text='Enter your shipping address')),
                ('quantity', models.PositiveIntegerField(help_text='Enter quantity you want to order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
