# Generated by Django 5.2.7 on 2025-10-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price in USD', max_digits=8)),
                ('quantity', models.PositiveIntegerField(help_text='Enter available stock quantity')),
                ('image', models.ImageField(blank=True, help_text='Upload a product image', null=True, upload_to='products/')),
            ],
        ),
    ]
